name:  Github Pages deployment

on:
  push:
    branches:
      - "main"

env: 
  REACT_APP_WEBSOCKET_SERVER: ${{ secrets.REACT_APP_WEBSOCKET_SERVER }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          token: ${{ secrets.GH_WORKFLOW_SECRET }}

      - name: Install and build
        run: npm install && npm run build

      - name: Deploy the site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
